version: "3.5"

# shared network to let these services connect to other containerized openstates services
networks:
  openstates-network:
      name: openstates-network

services:
  core:
    build: .
    environment:
      - DATABASE_URL=postgres://openstates:openstates@db/openstatesorg
    volumes:
      - .:/opt/openstates-core
    entrypoint: ["poetry", "run"]
    networks:
      - openstates-network
