name: Push to PyPi
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: install Poetry
        uses: snok/install-poetry@v1.3.3
      - name: configure pypi credentials
        run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
      - name: Publish package
        run: poetry publish --build
